### ISSUE TITLE
Error when deploy ODP

### ISSUE THREAD

**Issue by Natsuc0** [clemlabprojects/ambari#104]
I facing the following issue on the deployement step

OS : RHEL8
ODP : 1.2.2.0-138

stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 38, in <module>
    BeforeAnyHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 31, in hook
    setup_users()
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 58, in setup_users
    set_uid(params.smoke_user, params.smoke_user_dirs)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 147, in set_uid
    not_if = format("(test $(id -u {user}) -gt 1000) || ({ignore_groupsusers_create_str})"))
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0' returned 1. id: 'ambari-qa': no such user
Error: Error: Unable to run the custom hook script ['/usr/bin/python2', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-605.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-605.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']2024-11-29 13:59:11,252 - Reporting component version failed
Traceback (most recent call last):
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 367, in execute
    self.save_component_version_to_structured_out(self.command_name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 223, in save_component_version_to_structured_out
    stack_select_package_name = stack_select.get_package_name()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 116, in get_package_name
    package = get_packages(PACKAGE_SCOPE_STACK_SELECT, service_name, component_name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 230, in get_packages
    supported_packages = get_supported_packages()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 154, in get_supported_packages
    raise Fail("Unable to query for supported packages using {0}".format(stack_selector_path))
Fail: Unable to query for supported packages using /usr/bin/odp-select
 stdout:
2024-11-29 13:59:11,164 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=None -> 1.2
2024-11-29 13:59:11,169 - Using hadoop conf dir: /usr/odp/current/hadoop-client/conf
2024-11-29 13:59:11,170 - Group['kms'] {}
2024-11-29 13:59:11,172 - Group['livy'] {}
2024-11-29 13:59:11,172 - Group['spark'] {}
2024-11-29 13:59:11,172 - Group['ranger'] {}
2024-11-29 13:59:11,172 - Group['hdfs'] {}
2024-11-29 13:59:11,173 - Group['hue'] {}
2024-11-29 13:59:11,173 - Group['hadoop'] {}
2024-11-29 13:59:11,173 - Group['users'] {}
2024-11-29 13:59:11,173 - Group['knox'] {}
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,173 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - Skipping setting uid for hue user as unicorn need specific uid/gid
2024-11-29 13:59:11,174 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2024-11-29 13:59:11,176 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
Error: Error: Unable to run the custom hook script ['/usr/bin/python2', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-605.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-605.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']
2024-11-29 13:59:11,252 - Reporting component version failed
Traceback (most recent call last):
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 367, in execute
    self.save_component_version_to_structured_out(self.command_name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 223, in save_component_version_to_structured_out
    stack_select_package_name = stack_select.get_package_name()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 116, in get_package_name
    package = get_packages(PACKAGE_SCOPE_STACK_SELECT, service_name, component_name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 230, in get_packages
    supported_packages = get_supported_packages()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/functions/stack_select.py", line 154, in get_supported_packages
    raise Fail("Unable to query for supported packages using {0}".format(stack_selector_path))
Fail: Unable to query for supported packages using /usr/bin/odp-select

Command failed after 1 tries

**Comment by night-create** [comment]
yum install odp-select

**Comment by Natsuc0** [comment]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 38, in <module>
    BeforeAnyHook().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py", line 31, in hook
    setup_users()
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 58, in setup_users
    set_uid(params.smoke_user, params.smoke_user_dirs)
  File "/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/shared_initialization.py", line 147, in set_uid
    not_if = format("(test $(id -u {user}) -gt 1000) || ({ignore_groupsusers_create_str})"))
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0' returned 1. id: 'ambari-qa': no such user
Error: Error: Unable to run the custom hook script ['/usr/bin/python2', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY/scripts/hook.py', 'ANY', '/var/lib/ambari-agent/data/command-1079.json', '/var/lib/ambari-agent/cache/stack-hooks/before-ANY', '/var/lib/ambari-agent/data/structured-out-1079.json', 'INFO', '/var/lib/ambari-agent/tmp', 'PROTOCOL_TLSv1_2', '']2024-12-11 10:38:52,858 - The 'hadoop-hdfs-client' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (1.2.2.0-138). This is the version that will be reported.

**Comment by htcb0249** [comment]
I have the same problem in odp-select.
I found  that [clemlabprojects/ambari](https://github.com/clemlabprojects/ambari) · [ambari-server/src/main/resources/stacks/ODP/1.0/properties/stack_tools.json](https://github.com/clemlabprojects/ambari/blob/641b1878f7530759d9f63fce7bd58ae6c623a3f2/ambari-server/src/main/resources/stacks/ODP/1.0/properties/stack_tools.json#L4) has the dependecies of odp-select.
