### ISSUE TITLE
Error for start resurce manager yarn on odp 1.2.4 build 101 with ambari 2.7.11.0 build 110 on centos9 

### ISSUE THREAD

**Issue by simonj217** [clemlabprojects/ambari#113]
hi
@lucasbak 
I am using version 1.2.4 as per the title description on Red Hat 9, and I encounter an error when starting the Resource Manager. I will send you the related error. Even after manually setting the necessary permissions on the /service path, the problem still persists.”/service path, the problem still persists
======================================
stderr: 
NoneType: None

The above exception was the cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 261, in 
    Resourcemanager().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 350, in execute
    method(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 1012, in restart
    self.start(env, upgrade_type=upgrade_type)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 135, in start
    self.configure(env) # FOR SECURITY
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 62, in configure
    yarn(name='resourcemanager')
  File "/usr/lib/ambari-agent/lib/ambari_commons/os_family_impl.py", line 89, in thunk
    return fn(*args, **kwargs)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 372, in yarn
    setup_atsv2_backend(name,config_dir)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 650, in setup_atsv2_backend
    setup_system_services(config_dir)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 756, in setup_system_services
    params.HdfsResource(format("{user_dir}/hbase.yarnfile"),
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 164, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 163, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 127, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 682, in action_create_on_execute
    self.action_delayed("create")
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 679, in action_delayed
    self.get_hdfs_resource_executor().action_delayed(action_name, self)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 378, in action_delayed
    self.action_delayed_for_nameservice(None, action_name, main_resource)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 408, in action_delayed_for_nameservice
    self._create_resource()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 424, in _create_resource
    self._create_file(self.main_resource.resource.target, source=self.main_resource.resource.source, mode=self.mode)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 539, in _create_file
    self.util.run_command(target, 'CREATE', method='PUT', overwrite=True, assertable_result=False, file_to_put=source, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 214, in run_command
    return self._run_command(*args, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/providers/hdfs_resource.py", line 300, in _run_command
    raise WebHDFSCallException(err_msg, result_dict)
resource_management.libraries.providers.hdfs_resource.WebHDFSCallException: Execution of 'curl -sS -L -w '%{http_code}' -X PUT --data-binary @/usr/odp/1.2.4.0-101/hadoop/conf/embedded-yarn-ats-hbase/hbase.yarnfile -H 'Content-Type: application/octet-stream' 'http://m1.bigdata.local:50070/webhdfs/v1/services/sync/yarn-ats/hbase.yarnfile?op=CREATE&overwrite=True&user.name=hdfs'' returned status_code=403. 
{
  "RemoteException": {
    "exception": "IOException",
    "javaClassName": "java.io.IOException",
    "message": "File /services/sync/yarn-ats/hbase.yarnfile could only be written to 0 of the 1 minReplication nodes. There are 3 datanode(s) running and 3 node(s) are excluded in this operation.\n\tat org.apache.hadoop.hdfs.server.blockmanagement.BlockManager.chooseTarget4NewBlock(BlockManager.java:2350)\n\tat org.apache.hadoop.hdfs.server.namenode.FSDirWriteFileOp.chooseTargetForNewBlock(FSDirWriteFileOp.java:294)\n\tat org.apache.hadoop.hdfs.server.namenode.FSNamesystem.getAdditionalBlock(FSNamesystem.java:2989)\n\tat org.apache.hadoop.hdfs.server.namenode.NameNodeRpcServer.addBlock(NameNodeRpcServer.java:912)\n\tat org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolServerSideTranslatorPB.addBlock(ClientNamenodeProtocolServerSideTranslatorPB.java:595)\n\tat org.apache.hadoop.hdfs.protocol.proto.ClientNamenodeProtocolProtos$ClientNamenodeProtocol$2.callBlockingMethod(ClientNamenodeProtocolProtos.java)\n\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:621)\n\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:589)\n\tat org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:573)\n\tat org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1227)\n\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1094)\n\tat org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1017)\n\tat java.base/java.security.AccessController.doPrivileged(Native Method)\n\tat java.base/javax.security.auth.Subject.doAs(Subject.java:423)\n\tat org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1899)\n\tat org.apache.hadoop.ipc.Server$Handler.run(Server.java:3048)\n"
  }
}
 stdout:

**Comment by lucasbak** [comment]
@simonj217 

is hdfs healthy in your cluster ?

**Comment by simonj217** [comment]
@lucasbak 
yes it is ok.
![58987898558](https://github.com/user-attachments/assets/9f8ac6d4-b5f5-4139-ab04-a39c93faf77e)

**Comment by lucasbak** [comment]
@simonj217 

What is the alert ?

Do you see any error in the logs ?

**Comment by simonj217** [comment]
hi @lucasbak 
resurcemanager log
[log.txt](https://github.com/user-attachments/files/18254981/log.txt)

**Comment by simonj217** [comment]
hi @lucasbak 
resourcemanager log 
[log3.txt](https://github.com/user-attachments/files/18254988/log3.txt)

**Comment by simonj217** [comment]
hi @lucasbak 
I also installed the new cluster on Red Hat 8 on Ambari build 114 and odp 101, but it still gives an error.
=======================================================
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 261, in <module>
    Resourcemanager().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 350, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 135, in start
    self.configure(env) # FOR SECURITY
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/resourcemanager.py", line 62, in configure
    yarn(name='resourcemanager')
  File "/usr/lib/ambari-agent/lib/ambari_commons/os_family_impl.py", line 89, in thunk
    return fn(*args, **kwargs)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 372, in yarn
    setup_atsv2_backend(name,config_dir)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 650, in setup_atsv2_backend
    setup_system_services(config_dir)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/YARN/package/scripts/yarn.py", line 819, in setup_system_services
    params.HdfsResource(yarn_service_app_hdfs_path,
NameError: name 'yarn_service_app_hdfs_path' is not defined

**Comment by simonj217** [comment]
hi
@lucasbak 
I tested both on Redhat 9 and Redhat 8, both of them have problems, and when you can't load any  other service, you can't install and continue.

yum info ambari-server
Last metadata expiration check: 1:44:26 ago on Thu 26 Dec 2024 11:43:57 PM +0330.
Installed Packages
Name         : ambari-server
Version      : 2.7.11.0
Release      : 114
Architecture : x86_64
Size         : 980 M
Source       : ambari-server-2.7.11.0-114.src.rpm
Repository   : @System
From repo    : ambari
Summary      : Ambari Server
URL          : https://www.apache.org
License      : 2012, Apache Software Foundation
Description  : Maven Recipe: RPM Package.

[root@m1 ~]# cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

**Comment by aghazeh** [comment]
Hi
@lucasbak 
I have installed the cluster with RHEL 8, but the ResourceManager service in YARN won't start.
I would appreciate it if you could check this.
Ambari 2.7.11.0 build 117
Odp 1.2.4 -101
Thanks

**Comment by lucasbak** [comment]
@aghazeh 

Did you try with JDK 8 ?

**Comment by lucasbak** [comment]
@simonj217 

What is the exact error ?

Have you enough memory on the nodes ?

It should start without any problems. We fixed the permissions errors

Regards

**Comment by aghazeh** [comment]
No I installed openjdk 11. On redhat 8 and 9.

**Comment by simonj217** [comment]
?

**Comment by lucasbak** [comment]
Hi @simonj217,

Sorry for the delay.
It is happening only when Yarn Timeline V2 is installed.
The issue has been identified and being corrected.

Regards

**Comment by lucasbak** [comment]
@simonj217 ,

will tell you when ambari will be released

**Comment by lucasbak** [comment]
Hi @simonj217,

ambari 2.7.11.0.0-116 has bee released with the issue fixed.

Regards,

Wishing you an amazing 2025 year

Clemlab Team

**Comment by simonj217** [comment]
hi @lucasbak 
thanks a lot 
you too
