### ISSUE TITLE
【bug】Spark3  spark-sql with error: java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#15]
Please make sure that jars for your version of hive and hadoop are included in the paths passed to spark.sql.hive.metastore.jars.        
        at org.apache.spark.sql.errors.QueryExecutionErrors$.loadHiveClientCausesNoClassDefFoundError(QueryExecutionErrors.scala:1338)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:317)
        at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:496)
        at org.apache.spark.sql.hive.HiveUtils$.newClientForMetadata(HiveUtils.scala:356)
        at org.apache.spark.sql.hive.HiveExternalCatalog.client$lzycompute(HiveExternalCatalog.scala:71)
        at org.apache.spark.sql.hive.HiveExternalCatalog.client(HiveExternalCatalog.scala:70)
        at org.apache.spark.sql.hive.HiveExternalCatalog.$anonfun$databaseExists$1(HiveExternalCatalog.scala:224)
        at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
        at org.apache.spark.sql.hive.HiveExternalCatalog.withClient(HiveExternalCatalog.scala:102)
        at org.apache.spark.sql.hive.HiveExternalCatalog.databaseExists(HiveExternalCatalog.scala:224)
        at org.apache.spark.sql.internal.SharedState.externalCatalog$lzycompute(SharedState.scala:150)
        at org.apache.spark.sql.internal.SharedState.externalCatalog(SharedState.scala:140)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLEnv$.init(SparkSQLEnv.scala:64)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.<init>(SparkSQLCLIDriver.scala:328)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:160)
        at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:955)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:310)
        ... 26 more
Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/hive/conf/HiveConf
        at org.apache.spark.sql.hive.client.HiveClientImpl$.newHiveConf(HiveClientImpl.scala:1243)
        at org.apache.spark.sql.hive.client.HiveClientImpl.newState(HiveClientImpl.scala:164)
        at org.apache.spark.sql.hive.client.HiveClientImpl.<init>(HiveClientImpl.scala:129)
        ... 31 more
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.hive.conf.HiveConf
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1.doLoadClass(IsolatedClientLoader.scala:264)
        at org.apache.spark.sql.hive.client.IsolatedClientLoader$$anon$1.loadClass(IsolatedClientLoader.scala:253)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by lucasbak** [comment]
Hi,

How do you get the error ?
Which do you command do you run ?

Best regards,

**Comment by zyclove** [comment]
Finally, I modified the following configuration and it works fine.
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/15028279/178674798-7642e39c-300f-4a0a-8d29-88272caf1bf2.png">

**Comment by zyclove** [comment]
> Hi,
> 
> How do you get the error ? Which do you command do you run ?
> 
> Best regards,

After installing spark3 service，
just execute spark-sql in shell with spark user.

the config is the old verssion need to be upgraded.
/usr/hdp/{{version}}/spark3/standalone-metastore/standalone-metastore-1.21.2.{{version}}-hive3.jar

**Comment by lucasbak** [comment]
Hi,

Thanks for the report.
Does the value spark.sql.hive.metastore.jars: /usr/odp/current/spark3-client/standalone-metastore/* work for you ? in spark3-thrift-sparkconf ?

Best regards

**Comment by zyclove** [comment]
> Hi,
> 
> Thanks for the report. Does the value spark.sql.hive.metastore.jars: /usr/odp/current/spark3-client/standalone-metastore/* work for you ? in spark3-thrift-sparkconf ?
> 
> Best regards

no, but  hive-metastore (/usr/odp/current/hive-metastore/lib/* )  is ok.

**Comment by twosom** [comment]
> > 안녕,
> > 신고해 주셔서 감사합니다. Spark.sql.hive.metastore.jars: /usr/odp/current/spark3-client/standalone-metastore/* 값이 작동합니까? Spark3-thrift-sparkconf에서?
> > 친애하는
> 
> 아니요, 하지만 hive-metastore(/usr/odp/current/hive-metastore/lib/* )는 괜찮습니다.



> > Hi,
> > Thanks for the report. Does the value spark.sql.hive.metastore.jars: /usr/odp/current/spark3-client/standalone-metastore/* work for you ? in spark3-thrift-sparkconf ?
> > Best regards
> 
> no, but hive-metastore (/usr/odp/current/hive-metastore/lib/* ) is ok.

It works to me! thx!
