### ISSUE TITLE
Error installing Ranger Tagsync

### ISSUE THREAD

**Issue by kblaszczyk1** [clemlabprojects/ambari#30]
`stderr: 
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/RANGER/package/scripts/ranger_tagsync.py", line 133, in <module>
    RangerTagsync().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/RANGER/package/scripts/ranger_tagsync.py", line 44, in install
    setup_ranger_xml.ranger_credential_helper(params.tagsync_cred_lib, 'tagadmin.user.password', params.rangertagsync_user_password, params.tagsync_jceks_path)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/RANGER/package/scripts/setup_ranger_xml.py", line 586, in ranger_credential_helper
    Execute(cmd, environment={'JAVA_HOME': params.java_home}, logoutput=True, sudo=True)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-2.0.1.el8.x86_64/jre/bin/java -cp '/usr/odp/current/ranger-tagsync/lib/*' org.apache.ranger.credentialapi.buildks create tagadmin.user.password -value '[PROTECTED]' -provider jceks://file/usr/odp/current/ranger-tagsync/conf/rangertagsync.jceks' returned 1. Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/base/Preconditions
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:430)
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:443)
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:525)
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:39)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:87)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:41)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more
 stdout:
2023-09-30 03:36:17,181 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=None -> 1.2
2023-09-30 03:36:17,187 - Using hadoop conf dir: /usr/odp/1.2.1.0-134/hadoop/conf
2023-09-30 03:36:17,189 - Group['livy'] {}
2023-09-30 03:36:17,190 - Group['spark'] {}
2023-09-30 03:36:17,190 - Group['ranger'] {}
2023-09-30 03:36:17,190 - Group['hdfs'] {}
2023-09-30 03:36:17,190 - Group['hadoop'] {}
2023-09-30 03:36:17,190 - Group['users'] {}
2023-09-30 03:36:17,190 - Group['knox'] {}
2023-09-30 03:36:17,191 - User['yarn-ats'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,196 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,198 - User['infra-solr'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,201 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,204 - User['atlas'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,213 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,219 - User['ranger'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['ranger', 'hadoop'], 'uid': None}
2023-09-30 03:36:17,235 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2023-09-30 03:36:17,243 - User['livy'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['livy', 'hadoop'], 'uid': None}
2023-09-30 03:36:17,257 - User['spark'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['spark', 'hadoop'], 'uid': None}
2023-09-30 03:36:17,259 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2023-09-30 03:36:17,265 - User['kafka'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,281 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop'], 'uid': None}
2023-09-30 03:36:17,305 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,314 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,317 - User['hbase'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-09-30 03:36:17,321 - User['knox'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'knox'], 'uid': None}
2023-09-30 03:36:17,324 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-09-30 03:36:17,325 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2023-09-30 03:36:17,331 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2023-09-30 03:36:17,331 - Directory['/tmp/hbase-hbase'] {'owner': 'hbase', 'create_parents': True, 'mode': 0775, 'cd_access': 'a'}
2023-09-30 03:36:17,332 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-09-30 03:36:17,332 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-09-30 03:36:17,333 - call['/var/lib/ambari-agent/tmp/changeUid.sh hbase'] {}
2023-09-30 03:36:17,338 - call returned (0, '1015')
2023-09-30 03:36:17,338 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase 1015'] {'not_if': '(test $(id -u hbase) -gt 1000) || (false)'}
2023-09-30 03:36:17,342 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh hbase /home/hbase,/tmp/hbase,/usr/bin/hbase,/var/log/hbase,/tmp/hbase-hbase 1015'] due to not_if
2023-09-30 03:36:17,342 - Group['hdfs'] {}
2023-09-30 03:36:17,342 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop', u'hdfs']}
2023-09-30 03:36:17,344 - FS Type: HDFS
2023-09-30 03:36:17,344 - Directory['/etc/hadoop'] {'mode': 0755}
2023-09-30 03:36:17,353 - File['/usr/odp/1.2.1.0-134/hadoop/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2023-09-30 03:36:17,354 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2023-09-30 03:36:17,367 - Repository['ODP-1.2.1.0-21-repo-151'] {'base_url': 'http://odp-dev-mn-01.lan/ODP-1.2.1.0-134/', 'action': ['prepare'], 'components': [u'ODP', 'main'], 'repo_template': '[{{repo_id}}]\nname={{repo_id}}\n{% if mirror_list %}mirrorlist={{mirror_list}}{% else %}baseurl={{base_url}}{% endif %}\n\npath=/\nenabled=1\ngpgcheck=0', 'repo_file_name': 'ambari-odp-151', 'mirror_list': None}
2023-09-30 03:36:17,371 - Repository[None] {'action': ['create']}
2023-09-30 03:36:17,376 - File['/tmp/tmp0Rpcdp'] {'content': '[ODP-1.2.1.0-21-repo-151]\nname=ODP-1.2.1.0-21-repo-151\nbaseurl=http://odp-dev-mn-01.lan/ODP-1.2.1.0-134/\n\npath=/\nenabled=1\ngpgcheck=0'}
2023-09-30 03:36:17,376 - Writing File['/tmp/tmp0Rpcdp'] because contents don't match
2023-09-30 03:36:17,376 - File['/tmp/tmpD6QI4H'] {'content': StaticFile('/etc/yum.repos.d/ambari-odp-151.repo')}
2023-09-30 03:36:17,377 - Writing File['/tmp/tmpD6QI4H'] because contents don't match
2023-09-30 03:36:17,377 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-09-30 03:36:17,676 - Skipping installation of existing package unzip
2023-09-30 03:36:17,676 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-09-30 03:36:17,966 - Skipping installation of existing package curl
2023-09-30 03:36:17,969 - The repository with version 1.2.1.0-134 for this command has been marked as resolved. It will be used to report the version of the component which was installed
2023-09-30 03:36:18,180 - Package['ranger_1_2_1_0_134-admin'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-09-30 03:36:18,479 - Skipping installation of existing package ranger_1_2_1_0_134-admin
2023-09-30 03:36:18,480 - Package['ranger_1_2_1_0_134-usersync'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-09-30 03:36:18,780 - Skipping installation of existing package ranger_1_2_1_0_134-usersync
2023-09-30 03:36:18,781 - Package['ranger_1_2_1_0_134-tagsync'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-09-30 03:36:19,093 - Skipping installation of existing package ranger_1_2_1_0_134-tagsync
2023-09-30 03:36:19,094 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=None -> 1.2
2023-09-30 03:36:19,137 - Execute[(u'/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-2.0.1.el8.x86_64/jre/bin/java', '-cp', u'/usr/odp/current/ranger-tagsync/lib/*', 'org.apache.ranger.credentialapi.buildks', 'create', 'tagadmin.user.password', '-value', [PROTECTED], '-provider', u'jceks://file/usr/odp/current/ranger-tagsync/conf/rangertagsync.jceks')] {'logoutput': True, 'environment': {'JAVA_HOME': u'/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.382.b05-2.0.1.el8.x86_64/jre'}, 'sudo': True}
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/thirdparty/com/google/common/base/Preconditions
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:430)
	at org.apache.hadoop.conf.Configuration$DeprecationDelta.<init>(Configuration.java:443)
	at org.apache.hadoop.conf.Configuration.<clinit>(Configuration.java:525)
	at org.apache.ranger.credentialapi.CredentialReader.getDecryptedString(CredentialReader.java:39)
	at org.apache.ranger.credentialapi.buildks.createCredential(buildks.java:87)
	at org.apache.ranger.credentialapi.buildks.main(buildks.java:41)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.thirdparty.com.google.common.base.Preconditions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 6 more
2023-09-30 03:36:19,304 - The repository with version 1.2.1.0-134 for this command has been marked as resolved. It will be used to report the version of the component which was installed

Command failed after 1 tries
`
Hi, I'm trying to install the latest version of ODP and I keep getting this error when trying to install Ranger Tagsync

**Comment by lucasbak** [comment]
Hi @kblaszczyk1,

Thanks for the report.
We are going to check it.
Which Operating System do you use ?

Best regards,

Clemlab Team

**Comment by kblaszczyk1** [comment]
Thanks for reply!
I use Oracle Linux 8.6

**Comment by lucasbak** [comment]
Hi @kblaszczyk1 

We have identified the issue internally.
We are delivering a patch.
Will keep you update when it is ready.

Best regards,

Clemlab Team

**Comment by kblaszczyk1** [comment]
Hi @lucasbak ,

Thanks for your help and I wait for a patch
