### ISSUE TITLE
启动Spark3报错

### ISSUE THREAD

**Issue by SGITLOGIN** [clemlabprojects/ambari#38]
报错信息如下
stderr: 
2023-12-04 15:10:33,850 - The 'livy2-server' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (1.2.1.0-134). This is the version that will be reported.
2023-12-04 15:10:34,197 - The 'livy2-server' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (1.2.1.0-134). This is the version that will be reported.
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.2/services/SPARK3/package/scripts/livy2_server.py", line 148, in 
    LivyServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.2/services/SPARK3/package/scripts/livy2_server.py", line 62, in start
    self.configure(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.2/services/SPARK3/package/scripts/livy2_server.py", line 52, in configure
    setup_livy(env, 'server', upgrade_type=upgrade_type, action = 'config')
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.2/services/SPARK3/package/scripts/setup_livy2.py", line 57, in setup_livy
    setup_symlink(params.livy2_stack_conf, params.livy2_conf)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.2/services/SPARK3/package/scripts/setup_livy2.py", line 134, in setup_symlink
    to=src_livy2_conf_dir)
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 238, in action_create
    sudo.symlink(self.resource.to, path)
  File "/usr/lib/ambari-agent/lib/resource_management/core/sudo.py", line 130, in symlink
    os.symlink(source, link_name)
OSError: [Errno 2] No such file or directory
 stdout:
2023-12-04 15:10:33,556 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=1.2.1.0-134 -> 1.2.1.0-134
2023-12-04 15:10:33,574 - Using hadoop conf dir: /usr/odp/1.2.1.0-134/hadoop/conf
2023-12-04 15:10:33,691 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=1.2.1.0-134 -> 1.2.1.0-134
2023-12-04 15:10:33,696 - Using hadoop conf dir: /usr/odp/1.2.1.0-134/hadoop/conf
2023-12-04 15:10:33,697 - Group['livy'] {}
2023-12-04 15:10:33,698 - Group['spark'] {}
2023-12-04 15:10:33,698 - Group['hdfs'] {}
2023-12-04 15:10:33,698 - Group['hadoop'] {}
2023-12-04 15:10:33,698 - Group['users'] {}
2023-12-04 15:10:33,699 - User['hive'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,699 - User['yarn-ats'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,700 - User['livy'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['livy', 'hadoop'], 'uid': None}
2023-12-04 15:10:33,701 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,701 - User['spark'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['spark', 'hadoop'], 'uid': None}
2023-12-04 15:10:33,702 - User['ams'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,702 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2023-12-04 15:10:33,703 - User['tez'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop', 'users'], 'uid': None}
2023-12-04 15:10:33,704 - User['hdfs'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop'], 'uid': None}
2023-12-04 15:10:33,704 - User['yarn'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,705 - User['mapred'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-04 15:10:33,705 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-12-04 15:10:33,706 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2023-12-04 15:10:33,710 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2023-12-04 15:10:33,710 - Group['hdfs'] {}
2023-12-04 15:10:33,710 - User['hdfs'] {'fetch_nonlocal_groups': True, 'groups': ['hdfs', 'hadoop', u'hdfs']}
2023-12-04 15:10:33,711 - FS Type: HDFS
2023-12-04 15:10:33,711 - Directory['/etc/hadoop'] {'mode': 0755}
2023-12-04 15:10:33,725 - File['/usr/odp/1.2.1.0-134/hadoop/conf/hadoop-env.sh'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2023-12-04 15:10:33,725 - Directory['/var/lib/ambari-agent/tmp/hadoop_java_io_tmpdir'] {'owner': 'hdfs', 'group': 'hadoop', 'mode': 01777}
2023-12-04 15:10:33,738 - Execute[('setenforce', '0')] {'not_if': '(! which getenforce ) || (which getenforce && getenforce | grep -q Disabled)', 'sudo': True, 'only_if': 'test -f /selinux/enforce'}
2023-12-04 15:10:33,742 - Skipping Execute[('setenforce', '0')] due to not_if
2023-12-04 15:10:33,742 - Directory['/var/log/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'hadoop', 'mode': 0775, 'cd_access': 'a'}
2023-12-04 15:10:33,744 - Directory['/var/run/hadoop'] {'owner': 'root', 'create_parents': True, 'group': 'root', 'cd_access': 'a'}
2023-12-04 15:10:33,744 - Directory['/var/run/hadoop/hdfs'] {'owner': 'hdfs', 'cd_access': 'a'}
2023-12-04 15:10:33,745 - Directory['/tmp/hadoop-hdfs'] {'owner': 'hdfs', 'create_parents': True, 'cd_access': 'a'}
2023-12-04 15:10:33,748 - File['/usr/odp/1.2.1.0-134/hadoop/conf/commons-logging.properties'] {'content': Template('commons-logging.properties.j2'), 'owner': 'hdfs'}
2023-12-04 15:10:33,749 - File['/usr/odp/1.2.1.0-134/hadoop/conf/health_check'] {'content': Template('health_check.j2'), 'owner': 'hdfs'}
2023-12-04 15:10:33,754 - File['/usr/odp/1.2.1.0-134/hadoop/conf/log4j.properties'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop', 'mode': 0644}
2023-12-04 15:10:33,764 - File['/usr/odp/1.2.1.0-134/hadoop/conf/hadoop-metrics2.properties'] {'content': InlineTemplate(...), 'owner': 'hdfs', 'group': 'hadoop'}
2023-12-04 15:10:33,765 - File['/usr/odp/1.2.1.0-134/hadoop/conf/task-log4j.properties'] {'content': StaticFile('task-log4j.properties'), 'mode': 0755}
2023-12-04 15:10:33,766 - File['/usr/odp/1.2.1.0-134/hadoop/conf/configuration.xsl'] {'owner': 'hdfs', 'group': 'hadoop'}
2023-12-04 15:10:33,769 - File['/etc/hadoop/conf/topology_mappings.data'] {'owner': 'hdfs', 'content': Template('topology_mappings.data.j2'), 'only_if': 'test -d /etc/hadoop/conf', 'group': 'hadoop', 'mode': 0644}
2023-12-04 15:10:33,772 - File['/etc/hadoop/conf/topology_script.py'] {'content': StaticFile('topology_script.py'), 'only_if': 'test -d /etc/hadoop/conf', 'mode': 0755}
2023-12-04 15:10:33,774 - Skipping unlimited key JCE policy check and setup since the Java VM is not managed by Ambari
2023-12-04 15:10:33,828 - call[('ambari-python-wrap', u'/usr/bin/odp-select', 'versions')] {}
2023-12-04 15:10:33,849 - call returned (0, '1.2.1.0-134')
2023-12-04 15:10:33,850 - The 'livy2-server' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (1.2.1.0-134). This is the version that will be reported.
2023-12-04 15:10:33,977 - Using hadoop conf dir: /usr/odp/1.2.1.0-134/hadoop/conf
2023-12-04 15:10:33,989 - Verifying DFS directories where ATS stores time line data for active and completed applications.
2023-12-04 15:10:33,989 - Verifying if DFS directory '/ats/done/' exists.
2023-12-04 15:10:33,990 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c 'curl -sS -L -w '"'"'%{http_code}'"'"' -X GET -d '"'"''"'"' -H '"'"'Content-Length: 0'"'"' '"'"'http://ali-hadoop-slave-04:50070/webhdfs/v1/ats/done/?op=GETFILESTATUS&user.name=hdfs'"'"' 1>/tmp/tmpSIMuji 2>/tmp/tmpKnnL5l''] {'logoutput': None, 'quiet': False}
2023-12-04 15:10:34,022 - call returned (0, '')
2023-12-04 15:10:34,022 - get_user_call_output returned (0, u'{"FileStatus":{"accessTime":0,"blockSize":0,"childrenNum":0,"fileId":16390,"group":"hadoop","length":0,"modificationTime":1701672482043,"owner":"yarn","pathSuffix":"","permission":"700","replication":0,"storagePolicy":0,"type":"DIRECTORY"}}200', u'')
2023-12-04 15:10:34,022 - DFS directory '/ats/done/' exists.
2023-12-04 15:10:34,022 - Verifying if DFS directory '/ats/active/' exists.
2023-12-04 15:10:34,023 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c 'curl -sS -L -w '"'"'%{http_code}'"'"' -X GET -d '"'"''"'"' -H '"'"'Content-Length: 0'"'"' '"'"'http://ali-hadoop-slave-04:50070/webhdfs/v1/ats/active/?op=GETFILESTATUS&user.name=hdfs'"'"' 1>/tmp/tmpv4AQKZ 2>/tmp/tmpPziC5K''] {'logoutput': None, 'quiet': False}
2023-12-04 15:10:34,053 - call returned (0, '')
2023-12-04 15:10:34,054 - get_user_call_output returned (0, u'{"FileStatus":{"accessTime":0,"blockSize":0,"childrenNum":0,"fileId":16391,"group":"hadoop","length":0,"modificationTime":1701672482429,"owner":"yarn","pathSuffix":"","permission":"1777","replication":0,"storagePolicy":0,"type":"DIRECTORY"}}200', u'')
2023-12-04 15:10:34,054 - DFS directory '/ats/active/' exists.
2023-12-04 15:10:34,055 - Directory['/var/run/livy2'] {'owner': 'livy', 'create_parents': True, 'group': 'hadoop', 'mode': 0775, 'cd_access': 'a'}
2023-12-04 15:10:34,056 - Creating directory Directory['/var/run/livy2'] since it doesn't exist.
2023-12-04 15:10:34,056 - Changing owner for /var/run/livy2 from 0 to livy
2023-12-04 15:10:34,056 - Changing group for /var/run/livy2 from 0 to hadoop
2023-12-04 15:10:34,056 - Changing permission for /var/run/livy2 from 755 to 775
2023-12-04 15:10:34,057 - Directory['/var/log/livy2'] {'owner': 'livy', 'group': 'hadoop', 'create_parents': True, 'mode': 0775, 'cd_access': 'a'}
2023-12-04 15:10:34,057 - Creating directory Directory['/var/log/livy2'] since it doesn't exist.
2023-12-04 15:10:34,058 - Changing owner for /var/log/livy2 from 0 to livy
2023-12-04 15:10:34,058 - Changing group for /var/log/livy2 from 0 to hadoop
2023-12-04 15:10:34,058 - Changing permission for /var/log/livy2 from 755 to 775
2023-12-04 15:10:34,058 - HdfsResource['/user/livy'] {'security_enabled': False, 'hadoop_bin_dir': '/usr/odp/1.2.1.0-134/hadoop/bin', 'keytab': [EMPTY], 'dfs_type': 'HDFS', 'default_fs': 'hdfs://ali-hadoop-slave-04:8020', 'hdfs_resource_ignore_file': '/var/lib/ambari-agent/data/.hdfs_resource_ignore', 'hdfs_site': ..., 'kinit_path_local': 'kinit', 'principal_name': [EMPTY], 'user': 'hdfs', 'owner': 'livy', 'hadoop_conf_dir': '/usr/odp/1.2.1.0-134/hadoop/conf', 'type': 'directory', 'action': ['create_on_execute'], 'immutable_paths': [u'/user/hive/warehouse', u'/mr-history/done', u'/warehouse/tablespace/external/hive', u'/app-logs', u'/tmp'], 'mode': 0775}
2023-12-04 15:10:34,059 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c 'curl -sS -L -w '"'"'%{http_code}'"'"' -X GET -d '"'"''"'"' -H '"'"'Content-Length: 0'"'"' '"'"'http://ali-hadoop-slave-04:50070/webhdfs/v1/user/livy?op=GETFILESTATUS&user.name=hdfs'"'"' 1>/tmp/tmpKK8GEc 2>/tmp/tmp6q53iP''] {'logoutput': None, 'quiet': False}
2023-12-04 15:10:34,088 - call returned (0, '')
2023-12-04 15:10:34,089 - get_user_call_output returned (0, u'{"FileStatus":{"accessTime":0,"blockSize":0,"childrenNum":0,"fileId":16545,"group":"hdfs","length":0,"modificationTime":1701673490549,"owner":"livy","pathSuffix":"","permission":"775","replication":0,"storagePolicy":0,"type":"DIRECTORY"}}200', u'')
2023-12-04 15:10:34,089 - HdfsResource[None] {'security_enabled': False, 'hadoop_bin_dir': '/usr/odp/1.2.1.0-134/hadoop/bin', 'keytab': [EMPTY], 'dfs_type': 'HDFS', 'default_fs': 'hdfs://ali-hadoop-slave-04:8020', 'hdfs_resource_ignore_file': '/var/lib/ambari-agent/data/.hdfs_resource_ignore', 'hdfs_site': ..., 'kinit_path_local': 'kinit', 'principal_name': [EMPTY], 'user': 'hdfs', 'action': ['execute'], 'hadoop_conf_dir': '/usr/odp/1.2.1.0-134/hadoop/conf', 'immutable_paths': [u'/user/hive/warehouse', u'/mr-history/done', u'/warehouse/tablespace/external/hive', u'/app-logs', u'/tmp']}
2023-12-04 15:10:34,090 - HdfsResource['/livy2-recovery'] {'security_enabled': False, 'hadoop_bin_dir': '/usr/odp/1.2.1.0-134/hadoop/bin', 'keytab': [EMPTY], 'dfs_type': 'HDFS', 'default_fs': 'hdfs://ali-hadoop-slave-04:8020', 'hdfs_resource_ignore_file': '/var/lib/ambari-agent/data/.hdfs_resource_ignore', 'hdfs_site': ..., 'kinit_path_local': 'kinit', 'principal_name': [EMPTY], 'user': 'hdfs', 'owner': 'livy', 'hadoop_conf_dir': '/usr/odp/1.2.1.0-134/hadoop/conf', 'type': 'directory', 'action': ['create_on_execute'], 'immutable_paths': [u'/user/hive/warehouse', u'/mr-history/done', u'/warehouse/tablespace/external/hive', u'/app-logs', u'/tmp'], 'mode': 0700}
2023-12-04 15:10:34,091 - call['ambari-sudo.sh su hdfs -l -s /bin/bash -c 'curl -sS -L -w '"'"'%{http_code}'"'"' -X GET -d '"'"''"'"' -H '"'"'Content-Length: 0'"'"' '"'"'http://ali-hadoop-slave-04:50070/webhdfs/v1/livy2-recovery?op=GETFILESTATUS&user.name=hdfs'"'"' 1>/tmp/tmpnsRTFu 2>/tmp/tmp8aEKI8''] {'logoutput': None, 'quiet': False}
2023-12-04 15:10:34,123 - call returned (0, '')
2023-12-04 15:10:34,123 - get_user_call_output returned (0, u'{"FileStatus":{"accessTime":0,"blockSize":0,"childrenNum":0,"fileId":16546,"group":"hdfs","length":0,"modificationTime":1701673490671,"owner":"livy","pathSuffix":"","permission":"700","replication":0,"storagePolicy":0,"type":"DIRECTORY"}}200', u'')
2023-12-04 15:10:34,124 - HdfsResource[None] {'security_enabled': False, 'hadoop_bin_dir': '/usr/odp/1.2.1.0-134/hadoop/bin', 'keytab': [EMPTY], 'dfs_type': 'HDFS', 'default_fs': 'hdfs://ali-hadoop-slave-04:8020', 'hdfs_resource_ignore_file': '/var/lib/ambari-agent/data/.hdfs_resource_ignore', 'hdfs_site': ..., 'kinit_path_local': 'kinit', 'principal_name': [EMPTY], 'user': 'hdfs', 'action': ['execute'], 'hadoop_conf_dir': '/usr/odp/1.2.1.0-134/hadoop/conf', 'immutable_paths': [u'/user/hive/warehouse', u'/mr-history/done', u'/warehouse/tablespace/external/hive', u'/app-logs', u'/tmp']}
2023-12-04 15:10:34,130 - Directory['/usr/lib/ambari-logsearch-logfeeder/conf'] {'create_parents': True, 'mode': 0755, 'cd_access': 'a'}
2023-12-04 15:10:34,130 - Generate Log Feeder config file: /usr/lib/ambari-logsearch-logfeeder/conf/input.config-spark3.json
2023-12-04 15:10:34,130 - File['/usr/lib/ambari-logsearch-logfeeder/conf/input.config-spark3.json'] {'content': Template('input.config-spark3.json.j2'), 'mode': 0644}
2023-12-04 15:10:34,131 - Directory['/etc/spark3-livy2/conf'] {'group': 'hadoop', 'cd_access': 'a', 'create_parents': True, 'mode': 0750, 'owner': 'livy', 'recursive_ownership': True}
2023-12-04 15:10:34,131 - Creating directory Directory['/etc/spark3-livy2/conf'] since it doesn't exist.
2023-12-04 15:10:34,132 - Changing owner for /etc/spark3-livy2/conf from 0 to livy
2023-12-04 15:10:34,132 - Changing group for /etc/spark3-livy2/conf from 0 to hadoop
2023-12-04 15:10:34,133 - Link['/usr/odp/current/spark3-livy2-server/conf'] {'to': '/etc/spark3-livy2/conf'}
2023-12-04 15:10:34,133 - Creating symbolic Link['/usr/odp/current/spark3-livy2-server/conf'] to /etc/spark3-livy2/conf
2023-12-04 15:10:34,179 - call[('ambari-python-wrap', u'/usr/bin/odp-select', 'versions')] {}
2023-12-04 15:10:34,197 - call returned (0, '1.2.1.0-134')
2023-12-04 15:10:34,197 - The 'livy2-server' component did not advertise a version. This may indicate a problem with the component packaging. However, the stack-select tool was able to report a single version installed (1.2.1.0-134). This is the version that will be reported.

Command failed after 1 tries

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

Which version of ambari do you use ?

can you show also sterr.log file ?

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
@lucasbak  您好
ambari-release/2.7.8.0.0-104/repos-ambari.tar.gz
odp-utils/1.2.1.0/repos-utils.tar.gz
odp-release/1.2.1.0-134/repos.tar.gz
安装的是以上版本
上面包含了stderr所有日志，报错为OSError: [Errno 2] No such file or directory，但是不显示是找不到什么文件或目录
<img width="823" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d61d7a77-64a9-414c-9500-e0b5e2f29a30">

<img width="962" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0dc945e7-e9ad-47bf-8e8e-f5a184fb3e00">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
现在我重新删除了Spark3服务，并正在重建，红框中有两列都是Livy for Spark3 Server，有一列是Spark3 Thrift Server，我想问一下Livy for Spark3 Server是和那个服务对应的，我应该如何去选择Livy for Spark3 Server和Spark3 Thrift Server？

<img width="1624" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/523ef81b-73e9-4f30-bc8a-8438bd715484">

**Comment by SGITLOGIN** [comment]
您说的修复是指有多列Livy for Spark3 Server的问题吗？如果只是这个问题的话，我这边稍后会升级。
还有一个问题是我应该如何选择Livy for Spark3 Server和Spark3 Thrift Server，是所有节点都选择上吗

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

The fix concerns the number of columns normally you should have only one column !
Nope, only one node needs to be selected for Livy Spark Server.

Best regards

**Comment by SGITLOGIN** [comment]
@lucasbak 
您好，没有ambari-setup命令，目前已执行完yum upgrade ambari-server命令

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

The command is
`ambari-server upgrade`

Best regards,

**Comment by lucasbak** [comment]
the command are 
-  yum upgrade ambari* (it's ok regarding to your screenshot)
- ambari-server upgrade (to do on ambari-server host)

**Comment by lucasbak** [comment]
Alright.

We have reproduced the issue, working on a solution for RHEL based os

Best regards

**Comment by lucasbak** [comment]
Hi @SGITLOGIN ,

We have found the solution and providing you with the work around
Yes It's a bug only happening on RHEL.
There are missing packages to install that's why you have the Directory Does not exist error.

Workaround (tested on our cluster)
```bash
rpm -qa | grep livy | xargs rpm -e
yum install -y https://clemlabs.s3.eu-west-3.amazonaws.com/centos8/odp-release/1.2.1.0-134/rpms/spark3-livy2_1_2_1_0_134-0.8.0.1.2.1.0-134.el8.noarch.rpm
```
Should do the trick

For the columns you need to choose the second one.

Best regards,

Clemlab

**Comment by lucasbak** [comment]
<img width="1704" alt="Screenshot 2023-12-04 at 13 09 13" src="https://github.com/clemlabprojects/ambari/assets/4238285/4c4b5993-63da-47b7-a63b-5f07e57a78f0">
<img width="1725" alt="Screenshot 2023-12-04 at 13 10 33" src="https://github.com/clemlabprojects/ambari/assets/4238285/fc2c6aac-e601-40d0-ad68-aa1f8d881449">

**Comment by lucasbak** [comment]
Hi @SGITLOGIN, 

Any update ?

Best regards.

Clemlab Team

**Comment by SGITLOGIN** [comment]
您好，我这边还没有操作，明天我这边验证一下，验证完成我再回复您

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
我这边操作系统版本是CentOS7.9，我看您发的是CentOS8的包，这个我这边用的话会有什么问题吗？

**Comment by lucasbak** [comment]
Hi @SGITLOGIN,

We also build the fix for centos7.9 :).
```
rpm -qa | grep livy | xargs rpm -e
yum install -y https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-release/1.2.1.0-134/rpms/spark3-livy2_1_2_1_0_134-0.8.0.1.2.1.0-134.el7.noarch.rpm
```

Best regards,

Clemlab Team

**Comment by SGITLOGIN** [comment]
@lucasbak 
您好，安装报错
<img width="1211" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/dd4a4c54-7efd-4489-ab11-e58c27e1bebd">

**Comment by SGITLOGIN** [comment]
@lucasbak 
非常抱歉，漏了一步，执行完后，但是还是报错

<img width="1599" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/0d8ba4c5-2446-45cc-824c-14b56a796259">

**Comment by lucasbak** [comment]
no problems.

Do you have this error on install or during start ?

**Comment by SGITLOGIN** [comment]
@lucasbak 
我给您发一下操作步骤，您看一下是不是我操作的有问题
<img width="1603" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/a6a6c65d-bf47-4f6c-9557-9cc9295fa0f6">
<img width="1598" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/fb4bc446-b0b6-4ff5-be0f-9f60944da9c9">
<img width="1604" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/e26ae3d8-0229-44af-b558-b6de4bdcbdf9">
<img width="890" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/5cda180f-538a-4f57-8711-2433b7078b21">

**Comment by SGITLOGIN** [comment]
<img width="816" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/9fd291c6-ef1e-420c-8d7e-3d87697059cb">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
按照您的操作，我相当于是把livy2_1_2_1_0_134-0.7.0.1.2.1.0-134.el7.noarch给卸载了，然后安装了spark3-livy2_1_2_1_0_134-0.8.0.1.2.1.0-134.el7.noarch.rpm，现在安装的现象只要是卸载了livy2、安装了spark3-livy2的服务器报错都是Spark3客户端都安装失败

**Comment by lucasbak** [comment]
@SGITLOGIN ,

Thanks for the screenshot.
Trying to reproduce exactly steps to find solution

**Comment by SGITLOGIN** [comment]
@lucasbak 
好的，再跟您说一个现象，我现在已经将集群还原了，Spark2也会报同样的错误
<img width="1621" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/5e70796d-c733-4c9f-b3a6-f75c0f141968">

<img width="1522" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/7cf82ab7-51ae-4a94-8387-b7531eae95f7">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好

安装包都是下载下来，自己制作的本地仓库库
<img width="824" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/9938534e-5828-4971-bf86-e0a5f9bdd065">

下图为没有安装spark3-livy2时的状态
<img width="867" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/d566e4ee-38a3-47f5-8585-d0211f0b2b30">

下图为安装了spark3-livy2时的状态
<img width="972" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/2c8300b8-fe8c-4158-9a28-1f8058f25865">

**Comment by SGITLOGIN** [comment]
@lucasbak nin您好
我看您那边是livy2_1_2_1_0_134.noarch和spark3-livy2_1_2_1_0_134.noarch共存的，我这边如果已经安装了livy2_1_2_1_0_134.noarch，那么再次安装spark3-livy2_1_2_1_0_134.noarch是会报错的
<img width="1209" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/8f72f339-3217-4001-b1bf-b68607682054">

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
下图为我这边的信息
yum clean all
yum search livy2
yum info livy2_1_2_1_0_134.noarch

<img width="1215" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/61aaf399-c8a5-47e2-b30c-8652c8f8b50e">

**Comment by SGITLOGIN** [comment]
现在还有两个问题
1、repos-utils.tar.gz这个包有什么用，在安装的过程中没有要填写这个仓库的位置
2、LIVY FOR SPARK3 SERVER这个服务有什么作用，如果不安装，对提交任务和管理spark权限有什么影响吗

**Comment by SGITLOGIN** [comment]
现在还有两个问题
1、repos-utils.tar.gz这个包有什么用，在安装的过程中没有要填写这个仓库的位置
2、LIVY FOR SPARK3 SERVER这个服务有什么作用，如果不安装，对提交任务和管理spark权限有什么影响吗

**Comment by lucasbak** [comment]
@SGITLOGIN 

1. repos-utils is noot need for replacement it bring hdfs additional packages
2. Livy is for providing rest api over spark3 server, it will not remove spark3-submit nor pyspark functionalities

**Comment by SGITLOGIN** [comment]
https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-release/1.2.1.0-134/repos.tar.gz
您这边是什么时候更新的，我看和我的下载包的地址是一样

**Comment by lucasbak** [comment]
that's normal we have replace it for bringing fix to all our customers

**Comment by SGITLOGIN** [comment]
好的，我其他两个包需要重新下载吗？repos-ambari.tar.gz包还是用2.7.8.0.0-140吗，还是有最新版本的包？

wget https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/odp-utils/1.2.1.0/repos-utils.tar.gz
wget https://clemlabs.s3.eu-west-3.amazonaws.com/centos7/ambari-release/2.7.8.0.0-140/repos-ambari.tar.gz

**Comment by SGITLOGIN** [comment]
按照您刚才说的，即使Livy服务不安装也不会影响我提交spark任务和ranger对spark的权限管理，是这样吗？

**Comment by SGITLOGIN** [comment]
在最新的版本里面，多列的问题解决了吗

**Comment by SGITLOGIN** [comment]
好的，我重新装一下集群，还有我想问一下，新版本发布后会在哪里通知？以及在哪儿有变更记录，显示更新了什么功能？

**Comment by lucasbak** [comment]
It will be written in our release note.
We are currently improving documentation

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
ranger能够管控spark的spark-shell和spark-submit中的权限吗

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
还有个问题，每次我再重新搭建集群的时候，Check Tez操作总是失败
<img width="880" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/c3e559ca-97c7-4f98-8a63-6fa645e1b050">

**Comment by lucasbak** [comment]
@SGITLOGIN ,

1. Ranger does not allow to control spark-submit Access control
2. Sometimes the timeout can happen if hou have low sized host and slow host.

Is the cluster started ?

**Comment by lucasbak** [comment]
On the host in /var/log/spark3

**Comment by SGITLOGIN** [comment]
@lucasbak 您好
/var/log/spark3目录下只有这几个文件，是我这边配置项有问题吗？我这边还没有跑spark任务呢
<img width="1241" alt="image" src="https://github.com/clemlabprojects/ambari/assets/49664682/f006bec4-7e09-4c4e-ae31-9a3f97e5054b">

**Comment by lucasbak** [comment]
Did you install spark3 client ? nor change configuration ?

But in future version of ODP we are going to remove support for Spark3 Thrift Server so you don't need to install it
