### ISSUE TITLE
【bug】Error extracting ambari-views-package-2.7.6.0.0.jar

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#4]
ambari setup with ERROR 

Error extracting ambari-views-package-2.7.6.0.0.jar
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/15028279/159627935-5f1c8cff-fd22-4e00-9adb-d8b7fd2bd64f.png">

cat /var/log/ambari-server/ambari-server.log

2-03-23 04:51:21,451  INFO [main] Configuration:2867 - Generation of file with password
2022-03-23 04:51:22,021  INFO [main] ViewExtractor:89 - Creating archive folder /var/lib/ambari-server/resources/views/work/ADMIN_VIEW{2.7.6.0}.
2022-03-23 04:51:22,022  INFO [main] ViewExtractor:96 - Extracting files from ambari-admin-2.7.6.0.0.jar.
2022-03-23 04:51:22,662  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:51:22,876 ERROR [main] ViewRegistry:368 - Caught exception extracting view archive /var/lib/ambari-server/resources/views/ambari-views-package-2.7.6.0.0.jar.
java.lang.IllegalStateException: Archive /var/lib/ambari-server/resources/views/ambari-views-package-2.7.6.0.0.jar doesn't contain a view descriptor.
        at org.apache.ambari.server.view.ViewArchiveUtility.getViewConfigFromArchive(ViewArchiveUtility.java:75)
        at org.apache.ambari.server.view.ViewRegistry.extractViewArchive(ViewRegistry.java:2114)
        at org.apache.ambari.server.view.ViewRegistry.main(ViewRegistry.java:363)
2022-03-23 04:51:23,316  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:51:24,183  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:51:25,071  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:51:25,913  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:10,472  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:11,789  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:12,012 ERROR [main] ViewRegistry:368 - Caught exception extracting view archive /var/lib/ambari-server/resources/views/ambari-views-package-2.7.6.0.0.jar.
java.lang.IllegalStateException: Archive /var/lib/ambari-server/resources/views/ambari-views-package-2.7.6.0.0.jar doesn't contain a view descriptor.
        at org.apache.ambari.server.view.ViewArchiveUtility.getViewConfigFromArchive(ViewArchiveUtility.java:75)
        at org.apache.ambari.server.view.ViewRegistry.extractViewArchive(ViewRegistry.java:2114)
        at org.apache.ambari.server.view.ViewRegistry.main(ViewRegistry.java:363)
2022-03-23 04:59:12,462  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:13,328  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:14,218  INFO [main] Configuration:2880 - Reading password from existing file
2022-03-23 04:59:15,083  INFO [main] Configuration:2880 - Reading password from existing file

**Comment by yyounes75** [comment]
Hi,

You need to remove `/var/lib/ambari-server/resources/views/ambari-views-package-2.7.6.0.0.jar` et try `ambari-server setup`. It will be fixed on the next release soon.

**Comment by zyclove** [comment]
thanks

**Comment by yzewei** [comment]
Why does this problem occur?

**Comment by lucasbak** [comment]
Hi @yzewei,

This bug has been fixed in our latest releases.
Which version do you use ?


Best regards,

ClemlabTeam

**Comment by yzewei** [comment]
> Hi @yzewei,
> 
> This bug has been fixed in our latest releases. Which version do you use ?
> 
> Best regards,
> 
> ClemlabTeam

I want to figure out where this is a problem. Is it a question about the ambari-damin.jar compiled?
How to repair this problem?
THANKS!
