### ISSUE TITLE
can not install components in ambari 

### ISSUE THREAD

**Issue by aghazeh** [clemlabprojects/ambari#43]
hi
I want install odp cluster with componnets such as "zookeeper"
I had error such as bellow 
I am using Rocky Linux 8 with odp1.2 stack
stderr: 

Command aborted. Reason: 'Server considered task failed and automatically aborted it'
 stdout:
2023-12-31 13:13:05,487 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=None -> 1.2
2023-12-31 13:13:05,500 - Group['hadoop'] {}
2023-12-31 13:13:05,502 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-31 13:13:05,565 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-31 13:13:05,588 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-12-31 13:13:05,591 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2023-12-31 13:13:05,628 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2023-12-31 13:13:05,661 - Repository for ODP/1.2/ODP-1.2.1.0-21 is not managed by Ambari
2023-12-31 13:13:05,662 - Repository[None] {'action': ['create']}
2023-12-31 13:13:05,685 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-12-31 13:13:08,918 - Skipping installation of existing package unzip
2023-12-31 13:13:08,918 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-12-31 13:13:12,754 - Skipping installation of existing package curl
2023-12-31 13:13:13,049 - call[('ambari-python-wrap', u'/usr/bin/odp-select', 'versions')] {}
2023-12-31 13:13:13,148 - call returned (1, 'Traceback (most recent call last):\n  File "/usr/bin/odp-select", line 499, in \n    printVersions()\n  File "/usr/bin/odp-select", line 338, in printVersions\n    for f in os.listdir(root):\nOSError: [Errno 2] No such file or directory: \'/usr/odp\'')
2023-12-31 13:13:14,001 - Command repositories: ODP-1.2.1.0-21
2023-12-31 13:13:14,001 - Applicable repositories: ODP-1.2.1.0-21
2023-12-31 13:13:14,002 - Looking for matching packages in the following repositories: ODP-1.2.1.0-21
Command aborted. Reason: 'Server considered task failed and automatically aborted it'

Command failed after 1 tries

**Comment by aghazeh** [comment]
stderr: 
2023-12-31 13:22:58,881 - The 'zookeeper-server' component did not advertise a version. This may indicate a problem with the component packaging.
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/ZOOKEEPER/package/scripts/zookeeper_server.py", line 138, in 
    ZookeeperServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/ZOOKEEPER/package/scripts/zookeeper_server.py", line 67, in install
    self.install_packages(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 843, in install_packages
    name = self.format_package_name(package['name'])
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 566, in format_package_name
    return self.get_package_from_available(name)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 533, in get_package_from_available
    raise Fail("No package found for {0}(expected name: {1})".format(name, name_with_version))
resource_management.core.exceptions.Fail: No package found for zookeeper_${stack_version}(expected name: zookeeper_1_2)
 stdout:
2023-12-31 13:22:42,376 - Stack Feature Version Info: Cluster Stack=1.2, Command Stack=None, Command Version=None -> 1.2
2023-12-31 13:22:42,413 - Group['hadoop'] {}
2023-12-31 13:22:42,419 - User['zookeeper'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-31 13:22:42,468 - User['ambari-qa'] {'gid': 'hadoop', 'fetch_nonlocal_groups': True, 'groups': ['hadoop'], 'uid': None}
2023-12-31 13:22:42,496 - File['/var/lib/ambari-agent/tmp/changeUid.sh'] {'content': StaticFile('changeToSecureUid.sh'), 'mode': 0555}
2023-12-31 13:22:42,499 - Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] {'not_if': '(test $(id -u ambari-qa) -gt 1000) || (false)'}
2023-12-31 13:22:42,610 - Skipping Execute['/var/lib/ambari-agent/tmp/changeUid.sh ambari-qa /tmp/hadoop-ambari-qa,/tmp/hsperfdata_ambari-qa,/home/ambari-qa,/tmp/ambari-qa,/tmp/sqoop-ambari-qa 0'] due to not_if
2023-12-31 13:22:42,740 - Repository for ODP/1.2/ODP-1.2.1.0-21 is not managed by Ambari
2023-12-31 13:22:42,740 - Repository[None] {'action': ['create']}
2023-12-31 13:22:42,759 - Package['unzip'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-12-31 13:22:47,875 - Skipping installation of existing package unzip
2023-12-31 13:22:47,876 - Package['curl'] {'retry_on_repo_unavailability': False, 'retry_count': 5}
2023-12-31 13:22:51,579 - Skipping installation of existing package curl
2023-12-31 13:22:51,773 - call[('ambari-python-wrap', u'/usr/bin/odp-select', 'versions')] {}
2023-12-31 13:22:51,903 - call returned (1, 'Traceback (most recent call last):\n  File "/usr/bin/odp-select", line 499, in \n    printVersions()\n  File "/usr/bin/odp-select", line 338, in printVersions\n    for f in os.listdir(root):\nOSError: [Errno 2] No such file or directory: \'/usr/odp\'')
2023-12-31 13:22:52,841 - Command repositories: ODP-1.2.1.0-21
2023-12-31 13:22:52,841 - Applicable repositories: ODP-1.2.1.0-21
2023-12-31 13:22:52,842 - Looking for matching packages in the following repositories: ODP-1.2.1.0-21
2023-12-31 13:22:58,804 - call[('ambari-python-wrap', u'/usr/bin/odp-select', 'versions')] {}
2023-12-31 13:22:58,880 - call returned (1, 'Traceback (most recent call last):\n  File "/usr/bin/odp-select", line 499, in \n    printVersions()\n  File "/usr/bin/odp-select", line 338, in printVersions\n    for f in os.listdir(root):\nOSError: [Errno 2] No such file or directory: \'/usr/odp\'')
2023-12-31 13:22:58,881 - The 'zookeeper-server' component did not advertise a version. This may indicate a problem with the component packaging.

Command failed after 1 tries

**Comment by twosom** [comment]
maybe you can try to make dir from this message
`No such file or directory: '/usr/odp'`

**Comment by lucasbak** [comment]
Hi @aghazeh ,

The ODP Version is not the good one, you should use 1.2.1.0-134 as per the documentation.
1.2.1.0-21 was released during testing of ODP 1.2.1 builds 

Try with the proposed version and let us know if it does work

Best regards

**Comment by farshad-allahdadi** [comment]
Hi @lucasbak 
By ODP version, if you meant the rpms of components, it is 1.2.1.0-134.
But the stack number for odp stack is 1.2.10-21 included in Ambari server which i downloaded from:

**Comment by farshad-allahdadi** [comment]
Seems like that Ambari's rpms not updated, cause in source, the version is 134:
https://github.com/clemlabprojects/ambari/blob/2.7.8.0/ambari-server/src/main/resources/stacks/ODP/1.2/repos/repoinfo.xml

**Comment by lucasbak** [comment]
Hi,

Indeed Ambari contains an example for the VDF file. 1.2.1.0-21, here is a screenshot to show you how to specify  a different one when installing your cluster.
<img width="1726" alt="Screenshot 2024-01-01 at 22 42 09" src="https://github.com/clemlabprojects/ambari/assets/4238285/5f72ce27-bfc9-4ac8-b6b0-475d2d5a63d0">
For using 1.2.1.0-134 you can use this link https://clemlabs.s3.eu-west-3.amazonaws.com/centos8/odp-release/1.2.1.0-134/ODP-VDF.xml

Best regards

**Comment by farshad-allahdadi** [comment]
@lucasbak Thanks alot, that fixed the problem! Although I had to change two minor changes to VDF file:
<stack-id>ODP-1.0</stack-id> to <stack-id>ODP-1.2</stack-id>
<repoid>ODP-1.0</repoid> to       <repoid>ODP-1.2</repoid>

**Comment by lucasbak** [comment]
Hi @farshad-allahdadi 

Glad to see it fixed your problem :)
Indeed the change you made is also required for changing major Version.
@aghazeh did you try the fix ?

Best regards
