### ISSUE TITLE
【bug】add hive metastore with Failed to get schema version

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#5]
No rows affected (0.006 seconds)
0: jdbc:postgresql://master:5432/hive> CREATE INDEX IDX_RUNTIME_STATS_CREATE_TIM 
E ON RUNTIME_STATS(CREATE_TIME)
No rows affected (0.003 seconds)
0: jdbc:postgresql://master:5432/hive> INSERT INTO "VERSION" ("VER_ID", "SCHEMA_ 
VERSION", "VERSION_COMMENT") VALUES (1, '3.1.0', 'Hive release version 3.1.0')
1 row affected (0.001 seconds)
0: jdbc:postgresql://master:5432/hive> !closeall
Closing: 0: jdbc:postgresql://master:5432/hive
beeline> 
beeline> Initialization script completed
org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:ERROR: relation "VERSION" does not exist
 

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HIVE/package/scripts/hive_metastore.py", line 201, in <module>
    HiveMetastore().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HIVE/package/scripts/hive_metastore.py", line 61, in start
    create_metastore_schema() # execute without config lock
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HIVE/package/scripts/hive.py", line 476, in create_metastore_schema
    user = params.hive_user
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of 'export HIVE_CONF_DIR=/usr/odp/current/hive-metastore/conf/ ; /usr/odp/current/hive-server2/bin/schematool -initSchema -dbType postgres -userName hive -passWord [PROTECTED] -verbose' returned 1. SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/odp/1.0.3.0-270/hive/lib/log4j-slf4j-impl-2.10.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/odp/1.0.3.0-270/hadoop/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

org.apache.hadoop.hive.metastore.HiveMetaException: Failed to get schema version, Cause:ERROR: relation "VERSION" does not exist
  Position: 32
	at org.apache.hadoop.hive.metastore.MetaStoreSchemaInfo.getMetaStoreSchemaVersion(MetaStoreSchemaInfo.java:243)
	at org.apache.hive.beeline.HiveSchemaTool.verifySchemaVersion(HiveSchemaTool.java:493)
	at org.apache.hive.beeline.HiveSchemaTool.doInit(HiveSchemaTool.java:570)
	at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
*** schemaTool failed ***
<img width="807" alt="image" src="https://user-images.githubusercontent.com/15028279/160040029-debb4e14-a21f-4d42-bf86-176a0e47d7d3.png">
================================
restart with error,

No rows affected (0.007 seconds)
0: jdbc:postgresql://master:5432/hive> CREATE TABLE "BUCKETING_COLS" ( "SD_ID" b 
igint NOT NULL, "BUCKET_COL_NAME" character varying(256) DEFAULT NULL::character 
 varying, "INTEGER_IDX" bigint NOT NULL )
Error: ERROR: relation "BUCKETING_COLS" already exists (state=42P07,code=0)
Closing: 0: jdbc:postgresql://master:5432/hive
org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
Underlying cause: java.io.IOException : Schema script failed, errorcode 2
org.apache.hadoop.hive.metastore.HiveMetaException: Schema initialization FAILED! Metastore state would be inconsistent !!
	at org.apache.hive.beeline.HiveSchemaTool.doInit(HiveSchemaTool.java:594)
	at org.apache.hive.beeline.HiveSchemaTool.doInit(HiveSchemaTool.java:567)
	at org.apache.hive.beeline.HiveSchemaTool.main(HiveSchemaTool.java:1517)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
Caused by: java.io.IOException: Schema script failed, errorcode 2
	at org.apache.hive.beeline.HiveSchemaTool.runBeeLine(HiveSchemaTool.java:1226)
	at org.apache.hive.beeline.HiveSchemaTool.runBeeLine(HiveSchemaTool.java:1204)
	at org.apache.hive.beeline.HiveSchemaTool.doInit(HiveSchemaTool.java:590)
	... 8 more
*** schemaTool failed ***

**Comment by zyclove** [comment]
it’s wrong with hive privilege 

grant all on *.* to 'hive'@'%' identified by 'hive';

now it's ok.
