### ISSUE TITLE
Infra Solr start failed

### ISSUE THREAD

**Issue by farshad-allahdadi** [clemlabprojects/ambari#50]
Enabled Kerberos, then trying to install Ranger to authorize access to HDFS, Hive. It recommends to be installed with Infra Solr, so I tried to install Ranger and Infra Solr together, but Infra Solr failed to start:

KeeperErrorCode = NoAuth for /infra-solr
org.apache.zookeeper.KeeperException$NoAuthException: KeeperErrorCode = NoAuth for /infra-solr
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:120)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)

For now, just disabled Ranger auditing and deleted Infra Solr.
In Cloudera discussions someone suggested to use JDK8-252 (I'm using JDK8-350), not tried it yet

**Comment by lucasbak** [comment]
Hi @farshad-allahdadi,

Where do you have the error ? In Solr collection creation or Ambari Infra Solr Start ?

Here is test cluster, you can see that JAVA version is 392 ( the latest provided by Rocky/RHEL 8.8)

```bash
[root@master01 ~]# ps aux | grep solr
infra-s+   65591  0.4  5.3 7897480 1296228 ?     Sl   Jan06   7:35 /usr/lib/jvm/java/bin/java -server -Xms4096m -Xmx4096m -XX:NewRatio=3 -XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -verbose:gc -XX:+PrintHeapAtGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=15 -XX:GCLogFileSize=200M -Xloggc:/var/log/ambari-infra-solr/solr_gc.log -Xloggc:/var/log/ambari-infra-solr/solr_gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=9 -XX:GCLogFileSize=20M -Dsolr.jetty.inetaccess.includes= -Dsolr.jetty.inetaccess.excludes= -DzkClientTimeout=60000 -DzkHost=master01.clemlab.com:2181,master02.clemlab.com:2181,master03.clemlab.com:2181/infra-solr -Dsolr.log.dir=/var/log/ambari-infra-solr -Djetty.port=8886 -DSTOP.PORT=7886 -DSTOP.KEY=solrrocks -Dhost=master01.clemlab.com -Duser.timezone=UTC -XX:-OmitStackTraceInFastThrow -XX:OnOutOfMemoryError=/usr/lib/ambari-infra-solr/bin/oom_solr.sh 8886 /var/log/ambari-infra-solr -Djetty.home=/usr/lib/ambari-infra-solr/server -Dsolr.solr.home=/opt/ambari_infra_solr/data -Dsolr.data.home= -Dsolr.install.dir=/usr/lib/ambari-infra-solr -Dsolr.default.confdir=/usr/lib/ambari-infra-solr/server/solr/configsets/_default/conf -Dlog4j.configurationFile=/etc/ambari-infra-solr/conf/log4j2.xml -Djava.rmi.server.hostname=master01.clemlab.com -Dsolr.hdfs.security.kerberos.principal=infra-solr/master01.clemlab.com@CLEMLAB.COM -Dzookeeper.sasl.client=true -Dzookeeper.sasl.client.username=zookeeper -Dzookeeper.sasl.clientconfig=Client -Dsolr.kerberos.name.rules=DEFAULT -Xss1m -Dsolr.httpclient.builder.factory=org.apache.solr.client.solrj.impl.Krb5HttpClientBuilder -DauthenticationPlugin=org.apache.solr.security.KerberosPlugin -Djava.security.auth.login.config=/etc/ambari-infra-solr/conf/infra_solr_jaas.conf -Dsolr.kerberos.principal=HTTP/master01.clemlab.com@CLEMLAB.COM -Dsolr.kerberos.keytab=/etc/security/keytabs/spnego.service.keytab -solr.kerberos.cookie.domain=master01.clemlab.com -Dsolr.log.muteconsole -jar start.jar --module=http --module=gzip
root     1655474  0.0  0.0  12144  1184 pts/2    S+   15:29   0:00 grep --color=auto solr
[root@master01 ~]# java -version
openjdk version "1.8.0_392"
OpenJDK Runtime Environment (build 1.8.0_392-b08)
OpenJDK 64-Bit Server VM (build 25.392-b08, mixed mode)
```

Best regards

**Comment by farshad-allahdadi** [comment]
@lucasbak , in Ambari Infra Solr Start

**Comment by lucasbak** [comment]
@farshad-allahdadi you may have something wrong in your kerberos setup, are you using full or short fqdn ?

**Comment by farshad-allahdadi** [comment]
I had a single hostname which is my.host128.server
