### ISSUE TITLE
【bug】hbase phoenix-server start failed for queryserver.py

### ISSUE THREAD

**Issue by zyclove** [clemlabprojects/ambari#6]
Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 91, in <module>
    PhoenixQueryServer().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 975, in restart
    self.stop(env, upgrade_type=upgrade_type)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HBASE/package/scripts/phoenix_queryserver.py", line 57, in stop
    phoenix_service('stop')
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/HBASE/package/scripts/phoenix_service.py", line 47, in phoenix_service
    environment=env
  File "/usr/lib/ambari-agent/lib/resource_management/core/base.py", line 166, in __init__
    self.env.run()
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 160, in run
    self.run_action(resource, action)
  File "/usr/lib/ambari-agent/lib/resource_management/core/environment.py", line 124, in run_action
    provider_action()
  File "/usr/lib/ambari-agent/lib/resource_management/core/providers/system.py", line 263, in action_run
    returns=self.resource.returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 72, in inner
    result = function(command, **kwargs)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 102, in checked_call
    tries=tries, try_sleep=try_sleep, timeout_kill_strategy=timeout_kill_strategy, returns=returns)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 150, in _call_wrapper
    result = _call(command, **kwargs_copy)
  File "/usr/lib/ambari-agent/lib/resource_management/core/shell.py", line 314, in _call
    raise ExecutionFailed(err_msg, code, out, err)
resource_management.core.exceptions.ExecutionFailed: Execution of '/usr/odp/current/phoenix-server/bin/queryserver.py stop' returned 127. -bash: /usr/odp/current/phoenix-server/bin/queryserver.py: No such file or directory

**Comment by zyclove** [comment]
restart hbase with error:

2022-03-25 05:54:06,407 INFO  [main] impl.MetricsConfig: Loaded properties from hadoop-metrics2-hbase.properties
2022-03-25 05:54:06,662 INFO  [main] impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
2022-03-25 05:54:06,662 INFO  [main] impl.MetricsSystemImpl: HBase metrics system started
2022-03-25 05:54:06,704 INFO  [main] metrics.MetricRegistries: Loaded MetricRegistries class org.apache.hadoop.hbase.metrics.impl.MetricRegistriesImpl
2022-03-25 05:54:07,058 ERROR [main] regionserver.HRegionServer: Failed construction RegionServer
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hbase.ipc.PhoenixRpcSchedulerFactory not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2638)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRpcSchedulerFactoryClass(RSRpcServices.java:1292)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getRpcSchedulerFactoryClass(MasterRpcServices.java:376)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:1214)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:1204)
	at org.apache.hadoop.hbase.master.MasterRpcServices.<init>(MasterRpcServices.java:368)
	at org.apache.hadoop.hbase.master.HMaster.createRpcServices(HMaster.java:720)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:606)
	at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:494)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2937)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:236)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:140)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2955)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hbase.ipc.PhoenixRpcSchedulerFactory not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2542)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2636)
	... 18 more
2022-03-25 05:54:07,060 ERROR [main] master.HMasterCommandLine: Master exiting
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMaster.
	at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2944)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.startMaster(HMasterCommandLine.java:236)
	at org.apache.hadoop.hbase.master.HMasterCommandLine.run(HMasterCommandLine.java:140)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
	at org.apache.hadoop.hbase.util.ServerCommandLine.doMain(ServerCommandLine.java:149)
	at org.apache.hadoop.hbase.master.HMaster.main(HMaster.java:2955)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.hbase.ipc.PhoenixRpcSchedulerFactory not found
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2638)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.getRpcSchedulerFactoryClass(RSRpcServices.java:1292)
	at org.apache.hadoop.hbase.master.MasterRpcServices.getRpcSchedulerFactoryClass(MasterRpcServices.java:376)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:1214)
	at org.apache.hadoop.hbase.regionserver.RSRpcServices.<init>(RSRpcServices.java:1204)
	at org.apache.hadoop.hbase.master.MasterRpcServices.<init>(MasterRpcServices.java:368)
	at org.apache.hadoop.hbase.master.HMaster.createRpcServices(HMaster.java:720)
	at org.apache.hadoop.hbase.regionserver.HRegionServer.<init>(HRegionServer.java:606)
	at org.apache.hadoop.hbase.master.HMaster.<init>(HMaster.java:494)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.hbase.master.HMaster.constructMaster(HMaster.java:2937)
	... 5 more
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hbase.ipc.PhoenixRpcSchedulerFactory not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2542)
	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2636)
	... 18 more
