### ISSUE TITLE
Failed to start Ambari Metrics on ODP 1.2.2.0

### ISSUE THREAD

**Issue by Meikelrizkyhartawan** [clemlabprojects/ambari#80]
im trying to start ambari metrics with ODP 1.2.2.0 but failed with error some variable is not defined, target_hbase_jna_dir and src_hbase_jna_dir are the variable that need to be defined in /var/lib/ambari-agent/cache/stacks/ODP/1.0/services/AMBARI_METRICS/package/scripts/params_linux.py , i can add it manually but im not sure what value i need to add. what exactly value that i need to put in the variable ?

error logs :

Traceback (most recent call last):
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/AMBARI_METRICS/package/scripts/metrics_collector.py", line 90, in <module>
    AmsCollector().execute()
  File "/usr/lib/ambari-agent/lib/resource_management/libraries/script/script.py", line 352, in execute
    method(env)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/AMBARI_METRICS/package/scripts/metrics_collector.py", line 51, in start
    ams_service('collector', action = 'start')
  File "/usr/lib/ambari-agent/lib/ambari_commons/os_family_impl.py", line 89, in thunk
    return fn(*args, **kwargs)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/AMBARI_METRICS/package/scripts/ams_service.py", line 55, in ams_service
    hbase_service('master', action=action)
  File "/var/lib/ambari-agent/cache/stacks/ODP/1.0/services/AMBARI_METRICS/package/scripts/hbase_service.py", line 38, in hbase_service
    setup_symlink(params.target_hbase_jna_dir, params.src_hbase_jna_dir)
AttributeError: 'module' object has no attribute 'target_hbase_jna_dir'

**Comment by sachindhiman85** [comment]
Hi @lucasbak , I am getting the same issue. Please help to check.
