### ISSUE TITLE
Zeppelin fails to load due to requirements around needing zeppelin.interpreter.exclude and zeppelin.interpreter.include

### ISSUE THREAD

**Issue by lukefoskey** [clemlabprojects/ambari#96]
<img width="955" alt="image" src="https://github.com/user-attachments/assets/4380478c-9e2c-4d12-bce4-a8a44f9a3741">

It is not possible to install Zeppelin on 2.7.9.0 1.2.2.0 as it requires something for both of these fields, this causes zeppelin to fail to load

```Exception in thread "main" MultiException stack 1 of 8
java.io.IOException: zeppelin.interpreter.include and zeppelin.interpreter.exclude can not be specified together, only one can be set.
	at org.apache.zeppelin.interpreter.InterpreterSettingManager.init(InterpreterSettingManager.java:373)
	at org.apache.zeppelin.interpreter.InterpreterSettingManager.<init>(InterpreterSettingManager.java:200)
	at org.apache.zeppelin.interpreter.InterpreterSettingManager.<init>(InterpreterSettingManager.java:160)```

**Comment by lukefoskey** [comment]
Seems just a simple white space solves this, closing off
